apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: connectors.provider.coreos.com
spec:
  group: provider.coreos.com
  names:
    kind: Connector
    listKind: ConnectorList
    plural: connectors
    singular: connector
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
