apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devicetokens.provider.coreos.com
spec:
  group: provider.coreos.com
  names:
    kind: DeviceToken
    listKind: DeviceTokenList
    plural: devicetokens
    singular: devicetoken
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
