issuer: http://127.0.0.1:5556/provider

storage:
  type: sqlite3
  config:
    file: examples/provider.db

# Configuration for the HTTP endpoints.
web:
  http: 0.0.0.0:5556

grpc:
  addr: 127.0.0.1:5557
  tlsCert: server.crt
  tlsKey: server.key
  tlsClientCA: ca.crt

connectors:
- type: mockCallback
  id: mock
  name: Example

# Let provider keep a list of passwords which can be used to login to provider.
enablePasswordDB: true

